"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.readNetworkTicker = exports.readExternalAddressesCheck = exports.searchNetworkAsset = exports.readNetworkAsset = exports.readNetworkAssetsMultisig = exports.readNetworkAssetsTop = exports.readExternalTransactions = exports.readNetworkSnapshot = exports.readNetworkSnapshots = exports.readNetworkChains = void 0;
const http_1 = require("./http");
const readNetworkChains = () => (0, http_1.mixinRequest)('/network/chains');
exports.readNetworkChains = readNetworkChains;
// only support limit/offset/asset/order
const readNetworkSnapshots = (params) => (0, http_1.mixinRequest)('/network/snapshots', params);
exports.readNetworkSnapshots = readNetworkSnapshots;
const readNetworkSnapshot = (id) => (0, http_1.mixinRequest)(`/network/snapshots/${id}`);
exports.readNetworkSnapshot = readNetworkSnapshot;
const readExternalTransactions = (params) => (0, http_1.mixinRequest)('/external/transactions', params);
exports.readExternalTransactions = readExternalTransactions;
const readNetworkAssetsTop = () => (0, http_1.mixinRequest)('/network/assets/top');
exports.readNetworkAssetsTop = readNetworkAssetsTop;
const readNetworkAssetsMultisig = () => (0, http_1.mixinRequest)('/network/assets/multisig');
exports.readNetworkAssetsMultisig = readNetworkAssetsMultisig;
const readNetworkAsset = (id) => (0, http_1.mixinRequest)(`/network/assets/${id}`);
exports.readNetworkAsset = readNetworkAsset;
const searchNetworkAsset = (assetNameOrSymbol) => (0, http_1.mixinRequest)(`/network/assets/search/${assetNameOrSymbol}`);
exports.searchNetworkAsset = searchNetworkAsset;
const readExternalAddressesCheck = (params) => (0, http_1.mixinRequest)(`/external/addresses/check`, params);
exports.readExternalAddressesCheck = readExternalAddressesCheck;
const readNetworkTicker = (asset_id, offset) => (0, http_1.mixinRequest)(`/network/ticker`, { asset: asset_id, offset });
exports.readNetworkTicker = readNetworkTicker;
